site_name: Gyroflow


repo_url: https://github.com/gyroflow/gyroflow
copyright: © Gyroflow dev team  
edit_uri: ../gyroflow-docs/edit/main/docs

extra:
  homepage: https://gyroflow.xyz

theme:
  custom_dir: 'theme'
  name: material
  favicon: assets/images/favicon.png
  logo: assets/images/logo_small_white.svg
  palette:
    - media: "(prefers-color-scheme: light)" 

      scheme: default
      toggle:
        icon: material/eye-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 

      scheme: slate
      toggle:
        icon: material/eye
        name: Switch to light mode

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html
  - lightgallery:
      show_description_in_lightgallery: true
      show_description_as_inline_caption: true
      custom_inline_caption_css_class: 'lightbox-caption-class'
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - footnotes
  - tables

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/css/extra.css

nav:
    - Home: 'index.md'
    - 'User guide':
        - 'Quick start guide': 'guide/quickstart.md'
        - 'Installation': 'guide/installation.md'
        - 'Camera Calibration': 'guide/calibration.md'
        - 'Settings': 'guide/settings.md'

    - 'Gyro Logging':
        - 'General': 'logging/general.md'
        - 'Betaflight/INav/Cleanflight/etc.': 'logging/betaflight.md'
        - 'Flowbox': 'logging/flowbox.md'
        - 'Flowshutter':
            - 'Overview': 'logging/flowshutter/flowshutter.md'
            - 'DIY camera jacks': 'logging/flowshutter/diy camera jacks.md'
            - 'Supported camera list': 'logging/flowshutter/camera list.md'
        - 'Action cam as logger': "logging/actioncamlogger.md"
        - 'Custom hardware/logger': 'logging/customlogger.md'
        - 'Gyroflow .gcsv reference': 'logging/gcsv.md'

    - 'Camera setup guides':
        - 'General': 'cams/general.md'
        - 'GoPro': 'cams/gopro.md'
        - 'Runcam': 'cams/runcam.md'
        - 'Sony': 'cams/sony.md'
        - 'Insta360': 'cams/insta360.md'

    - 'Plugins and integrations':
        - 'OpenFX Plugin': 'integrations/OpenFX.md'

    - 'Technical info':
        - 'Filtering and noise': 'tech/filtering.md'
        - 'Orientations and smoothing': 'tech/smoothing.md'
        - 'Rolling Shutter': 'tech/rollingshutter.md'
        - 'Related Projects/Literature': 'tech/relatedprojects.md'
    - 'Contribute to the project':
        - 'Gyroflow': 'contrib/gyroflow.md'
        - 'Documentation': 'contrib/documentation.md'
        - 'Support Gyroflow / Contributors list': 'contrib/support.md'

